"""create celery_task_executions table

Revision ID: 4cacc8bc7dc1
Revises: 96b88e49805d
Create Date: 2025-11-10 18:02:23.488182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cacc8bc7dc1'
down_revision: Union[str, None] = '96b88e49805d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('collection_384_5_vector_idx', table_name='collection_384_5', postgresql_using='hnsw')
    op.drop_table('collection_384_5')
    op.drop_table('collection_384_2')
    op.alter_column('assets', 'asset_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'asset_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_table('collection_384_2',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_2_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_2_pkey')
    )
    op.create_table('collection_384_5',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_5_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_5_pkey')
    )
    op.create_index('collection_384_5_vector_idx', 'collection_384_5', ['vector'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
