"""update indexes

Revision ID: c14462129150
Revises: b04720e2dc52
Create Date: 2025-11-10 18:56:43.694867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14462129150'
down_revision: Union[str, None] = 'b04720e2dc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_hash', table_name='celery_task_executions')
    op.create_index('ix_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_celery_hash', table_name='celery_task_executions')
    op.create_index('ix_task_name_args_hash', 'celery_task_executions', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###
